'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let groups=[],instruments=[],attendanceData=[],gradeData=[],activeActivity=null,excelState=null,gradingData=null,deferredInstall=null;
const today=new Date().toISOString().slice(0,10);
const storeNames=['groups','students','attendance','activities','grades','instruments','evaluations','gradingSchemes','studentComponents','meta'];
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(error?' error':'');setTimeout(()=>t.className='toast',2800)}
function fmtNum(v,d=2){return v==null||Number.isNaN(+v)?'—':Number(v).toFixed(d).replace(/\.00$/,'')}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function goView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+name)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent={dashboard:'Inicio',groups:'Mis grupos',attendance:'Asistencia',activities:'Calificaciones',grading:'Calificación trimestral',evaluation:'Evaluación',more:'Más'}[name]||name;if(name==='dashboard')loadSummary();if(name==='activities')loadActivities();if(name==='grading')loadGrading();if(name==='evaluation'){loadInstruments();loadEvalStudents();loadEvalHistory()}}
window.goView=goView;
$$('.nav-item').forEach(b=>b.onclick=()=>goView(b.dataset.view));$('#quickAttendance').onclick=()=>goView('attendance');
const fmtDate=new Intl.DateTimeFormat('es-MX',{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('#todayLabel').textContent=fmtDate.format(new Date());$('#attendanceDate').value=today;$('#activityDate').value=today;$('#evalDate').value=today;

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').onclick=async()=>{if(!deferredInstall){toast('En Chrome abre el menú ⋮ y elige “Instalar aplicación” o “Agregar a pantalla principal”.');return}deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')};
window.addEventListener('appinstalled',()=>toast('MiAula quedó instalada'));
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('sw.js').catch(()=>{});

async function init(){try{await MiAulaDB.open();$('#systemStatus').textContent='Almacenamiento local listo · funciona sin laptop';await refreshGroups();await loadInstruments();await loadSummary();addCriterion()}catch(e){const b=$('#fatalBanner');b.textContent='No se pudo iniciar el almacenamiento local de MiAula: '+e.message;b.classList.remove('hidden');toast(e.message,true)}}

async function refreshGroups(){groups=(await MiAulaDB.all('groups')).filter(g=>g.active!==0).sort((a,b)=>String(a.grade).localeCompare(String(b.grade),'es',{numeric:true})||String(a.name).localeCompare(String(b.name),'es',{numeric:true}));const options='<option value="">Seleccionar…</option>'+groups.map(g=>`<option value="${g.id}">${escapeHtml(g.name)} — ${escapeHtml(g.discipline||'')}</option>`).join('');['#importGroup','#attendanceGroup','#activityGroup','#activityFilter','#gradingGroup','#evalGroup','#exportGroup'].forEach(id=>{if($(id))$(id).innerHTML=options});renderGroupsTable()}
async function loadSummary(){const students=await MiAulaDB.all('students'),attendance=await MiAulaDB.all('attendance'),grades=await MiAulaDB.all('grades'),activities=await MiAulaDB.all('activities');const activeIds=new Set(groups.map(g=>g.id)),activeStudents=students.filter(s=>activeIds.has(s.group_id)),studentIds=new Set(activeStudents.map(s=>s.id));const att=attendance.filter(a=>studentIds.has(a.student_id));const avgAtt=att.length?(100*att.filter(a=>a.status!=='F').length/att.length).toFixed(1)+'%':'—';const actMap=new Map(activities.map(a=>[a.id,a]));const normGrades=grades.filter(g=>studentIds.has(g.student_id)&&g.score!=null&&actMap.get(g.activity_id)?.max_score>0).map(g=>+g.score*10/+actMap.get(g.activity_id).max_score);const avg=normGrades.length?(normGrades.reduce((a,b)=>a+b,0)/normGrades.length).toFixed(1):'—';$('#kpis').innerHTML=[['Grupos',groups.length],['Alumnos',activeStudents.length],['Asistencia',avgAtt],['Promedio',avg]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const cards=[];for(const g of groups){const ss=activeStudents.filter(s=>s.group_id===g.id),ids=new Set(ss.map(s=>s.id)),ga=att.filter(a=>ids.has(a.student_id));cards.push(`<div class="group-card"><div class="grade">${escapeHtml(g.name)}</div><div class="disc">${escapeHtml(g.discipline||'')}</div><div class="group-stats"><span>${ss.length} alumnos</span><span>${ga.length?(100*ga.filter(a=>a.status!=='F').length/ga.length).toFixed(0)+'%':'—'} asistencia</span></div></div>`)}$('#dashboardGroups').innerHTML=cards.length?cards.join(''):'<div class="empty-state">Crea tu primer grupo o migra tu información de MiAula 2.4.1.</div>'}

$('#groupForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.active=1;d.created_at=new Date().toISOString();try{await MiAulaDB.add('groups',d);e.target.reset();e.target.school_year.value='2026-2027';await refreshGroups();await loadSummary();toast('Grupo creado')}catch(er){toast(er.message,true)}};
async function renderGroupsTable(){if(!groups.length){$('#groupsTable').innerHTML='<div class="empty-state">Todavía no hay grupos.</div>';return}const rows=[];for(const g of groups){const s=await MiAulaDB.byIndex('students','group_id',g.id);rows.push(`<tr><td><strong>${escapeHtml(g.name)}</strong></td><td>${escapeHtml(g.grade||'')}</td><td>${escapeHtml(g.discipline||'')}</td><td>${s.length}</td><td><div class="action-row"><button class="btn small" onclick="viewStudents(${g.id})">Alumnos</button><button class="btn small" onclick="editGroup(${g.id})">Editar</button><button class="btn small danger" onclick="archiveGroup(${g.id})">Archivar</button></div></td></tr>`)}$('#groupsTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Grupo</th><th>Grado</th><th>Disciplina</th><th>Alumnos</th><th>Acciones</th></tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
window.viewStudents=async gid=>{const s=(await MiAulaDB.byIndex('students','group_id',gid)).sort((a,b)=>(a.list_number??9999)-(b.list_number??9999)||a.name.localeCompare(b.name));const g=groups.find(x=>x.id===gid);$('#groupsTable').innerHTML=`<div class="panel-head"><div><h3>${escapeHtml(g.name)} · ${s.length} alumnos</h3><p>${escapeHtml(g.discipline)}</p></div><button class="btn" onclick="renderGroupsTable()">Volver</button></div><form id="manualStudentForm" class="form-grid"><input type="hidden" name="group_id" value="${gid}"><label>No. lista<input type="number" name="list_number" min="1"></label><label>Grado<input name="grade" value="${escapeHtml(g.grade||'')}"></label><label class="span-2">Nombre del alumno<input name="name" required placeholder="Nombre completo"></label><button class="btn primary span-2">Agregar alumno</button></form><div class="table-wrap"><table><thead><tr><th>No.</th><th>Código</th><th>Alumno</th><th>Grado</th><th></th></tr></thead><tbody>${s.map(x=>`<tr><td>${x.list_number??''}</td><td>${escapeHtml(x.student_code||'')}</td><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.grade||'')}</td><td><div class="action-row"><button class="btn small" onclick="editStudent(${x.id})">Editar</button><button class="btn small danger" onclick="deleteStudent(${x.id},${gid})">Eliminar</button></div></td></tr>`).join('')}</tbody></table></div>`;$('#manualStudentForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.group_id=+d.group_id;d.list_number=d.list_number?+d.list_number:null;d.student_code=await MiAulaDB.nextStudentCode();d.created_at=new Date().toISOString();await MiAulaDB.add('students',d);toast('Alumno agregado');viewStudents(gid);loadSummary()}}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
window.editGroup=async id=>{const g=await MiAulaDB.get('groups',id);openModal('Editar grupo',`<form id="editGroupForm"><label>Grupo<input name="name" value="${escapeHtml(g.name)}" required></label><label>Grado<input name="grade" value="${escapeHtml(g.grade||'')}"></label><label>Disciplina<input name="discipline" value="${escapeHtml(g.discipline||'')}" required></label><label>Ciclo escolar<input name="school_year" value="${escapeHtml(g.school_year||'')}"></label><button class="btn primary wide">Guardar cambios</button></form>`);$('#editGroupForm').onsubmit=async e=>{e.preventDefault();Object.assign(g,Object.fromEntries(new FormData(e.target)));await MiAulaDB.put('groups',g);closeModal();await refreshGroups();await loadSummary();toast('Grupo actualizado')}};
window.archiveGroup=async id=>{if(!confirm('¿Archivar este grupo? Sus datos se conservarán, pero dejará de aparecer en las listas activas.'))return;await MiAulaDB.archiveGroup(id);await refreshGroups();loadSummary();toast('Grupo archivado')};
window.editStudent=async id=>{const s=await MiAulaDB.get('students',id);openModal('Editar alumno',`<form id="editStudentForm"><label>Número de lista<input type="number" name="list_number" value="${s.list_number??''}"></label><label>Nombre<input name="name" value="${escapeHtml(s.name)}" required></label><label>Grado<input name="grade" value="${escapeHtml(s.grade||'')}"></label><button class="btn primary wide">Guardar cambios</button></form>`);$('#editStudentForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));s.list_number=d.list_number?+d.list_number:null;s.name=d.name.trim();s.grade=d.grade.trim();await MiAulaDB.put('students',s);closeModal();viewStudents(s.group_id);loadSummary();toast('Alumno actualizado')}};
window.deleteStudent=async(id,gid)=>{if(!confirm('¿Eliminar al alumno? También se borrarán sus asistencias, calificaciones y evaluaciones.'))return;await MiAulaDB.cascadeDeleteStudent(id);viewStudents(gid);loadSummary();toast('Alumno eliminado')};

$('#excelFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{toast('Leyendo Excel…');const book=await XLSXLite.read(await f.arrayBuffer());if(!book.sheets.length)throw new Error('El libro no contiene hojas legibles.');excelState={book,fileName:f.name};renderExcelWizard(0);toast('Excel leído correctamente')}catch(er){toast(er.message,true);e.target.value=''}};
function selectOpts(headers,sel){return '<option value="-1">No usar</option>'+headers.map((h,i)=>`<option value="${i}" ${i===sel?'selected':''}>${escapeHtml(h||('Columna '+(i+1)))}</option>`).join('')}
function renderExcelWizard(si){const sheet=excelState.book.sheets[si],d=XLSXLite.detectTable(sheet);excelState.table=d;const opt=(v)=>selectOpts(d.headers,v);$('#excelWizard').classList.remove('hidden');$('#excelWizard').innerHTML=`<label>Hoja<select id="wizSheet">${excelState.book.sheets.map((s,i)=>`<option value="${i}" ${i===si?'selected':''}>${escapeHtml(s.name)}</option>`).join('')}</select></label><div class="form-grid"><label class="span-2">Nombre del alumno *<select id="mapName">${opt(d.mapping.name)}</select></label><label>Número de lista<select id="mapNum">${opt(d.mapping.list_number)}</select></label><label>Grado<select id="mapGrade">${opt(d.mapping.grade)}</select></label></div><div class="table-wrap"><table><thead><tr>${d.headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${d.preview.map(r=>`<tr>${d.headers.map((_,i)=>`<td>${escapeHtml(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><button class="btn primary wide" id="confirmImport">Importar alumnos</button>`;$('#wizSheet').onchange=e=>renderExcelWizard(+e.target.value);$('#confirmImport').onclick=importExcel}
async function importExcel(){const gid=+$('#importGroup').value;if(!gid){toast('Selecciona el grupo destino',true);return}const si=+$('#wizSheet').value,sheet=excelState.book.sheets[si],d=XLSXLite.detectTable(sheet),nameIdx=+$('#mapName').value,numIdx=+$('#mapNum').value,gradeIdx=+$('#mapGrade').value;if(nameIdx<0){toast('Indica la columna del nombre',true);return}const existing=await MiAulaDB.byIndex('students','group_id',gid),names=new Set(existing.map(s=>s.name.trim().toLowerCase()));let imported=0,skipped=0;for(const row of sheet.rows.slice(d.headerRow+1)){const name=String(row[nameIdx]??'').trim();if(!name)continue;if(names.has(name.toLowerCase())){skipped++;continue}let num=null;if(numIdx>=0&&row[numIdx]!==''&&row[numIdx]!=null){const n=Number(row[numIdx]);if(Number.isFinite(n))num=Math.trunc(n)}const grade=gradeIdx>=0?String(row[gradeIdx]??'').trim():'';await MiAulaDB.add('students',{student_code:await MiAulaDB.nextStudentCode(),list_number:num,name,grade,group_id:gid,created_at:new Date().toISOString()});names.add(name.toLowerCase());imported++}$('#excelWizard').classList.add('hidden');$('#excelFile').value='';await renderGroupsTable();await loadSummary();toast(`${imported} alumnos importados${skipped?`, ${skipped} omitidos`:''}`)}

$('#loadAttendance').onclick=loadAttendance;async function loadAttendance(){const gid=+$('#attendanceGroup').value,dt=$('#attendanceDate').value;if(!gid){toast('Selecciona un grupo',true);return}const students=(await MiAulaDB.byIndex('students','group_id',gid)).sort((a,b)=>(a.list_number??9999)-(b.list_number??9999)||a.name.localeCompare(b.name)),records=await MiAulaDB.byIndex('attendance','group_date',[gid,dt]),map=new Map(records.map(r=>[r.student_id,r]));attendanceData=students.map(s=>({student_id:s.id,list_number:s.list_number,name:s.name,status:map.get(s.id)?.status||'P',notes:map.get(s.id)?.notes||'',id:map.get(s.id)?.id}));$('#attendanceList').className='student-list';$('#attendanceList').innerHTML=attendanceData.length?attendanceData.map((s,i)=>`<div class="student-row"><div class="num">${s.list_number??'—'}</div><strong>${escapeHtml(s.name)}</strong><div class="status-buttons">${['P','F','R','J'].map(st=>`<button class="status-btn ${s.status===st?'active':''}" data-status="${st}" onclick="setStatus(${i},'${st}',this)">${st}</button>`).join('')}</div></div>`).join(''):'<div class="empty-state">Este grupo no tiene alumnos.</div>';$('#saveAttendance').classList.toggle('hidden',!attendanceData.length)}
window.setStatus=(i,st,el)=>{attendanceData[i].status=st;el.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));el.classList.add('active')};
$('#saveAttendance').onclick=async()=>{const gid=+$('#attendanceGroup').value,dt=$('#attendanceDate').value;for(const it of attendanceData){const row={group_id:gid,student_id:it.student_id,attendance_date:dt,status:it.status,notes:it.notes||''};const old=await MiAulaDB.firstByIndex('attendance','unique_key',[gid,it.student_id,dt]);if(old)row.id=old.id;await MiAulaDB.put('attendance',row)}toast('Asistencia guardada');loadSummary()};

$('#activityForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.group_id){toast('Selecciona un grupo',true);return}d.group_id=+d.group_id;d.max_score=+d.max_score;d.weight=+d.weight;d.created_at=new Date().toISOString();await MiAulaDB.add('activities',d);e.target.title.value='';$('#activityFilter').value=d.group_id;await loadActivities();toast('Actividad creada')};$('#activityFilter').onchange=loadActivities;
async function loadActivities(){const gid=+($('#activityFilter').value||$('#activityGroup').value||groups[0]?.id||0);if(!gid){$('#activityCards').innerHTML='<div class="empty-state">Crea un grupo primero.</div>';return}$('#activityFilter').value=gid;const arr=(await MiAulaDB.byIndex('activities','group_id',gid)).sort((a,b)=>b.id-a.id);$('#activityCards').innerHTML=arr.length?arr.map(a=>`<div class="activity-card"><div><strong>${escapeHtml(a.title)}</strong><br><small>${escapeHtml(a.activity_type)} · Trim. ${a.period} · Máx. ${a.max_score} · Peso ${a.weight}</small></div><div class="action-row"><button class="btn small" onclick="openGrades(${a.id})">Calificar</button><button class="btn small danger" onclick="deleteActivity(${a.id})">Eliminar</button></div></div>`).join(''):'<div class="empty-state">No hay actividades para este grupo.</div>'}
window.openGrades=async aid=>{const a=await MiAulaDB.get('activities',aid);if(!a)return;activeActivity=a;const students=(await MiAulaDB.byIndex('students','group_id',a.group_id)).sort((x,y)=>(x.list_number??9999)-(y.list_number??9999)||x.name.localeCompare(y.name)),existing=await MiAulaDB.byIndex('grades','activity_id',aid),map=new Map(existing.map(g=>[g.student_id,g]));gradeData=students.map(s=>({student_id:s.id,list_number:s.list_number,name:s.name,score:map.get(s.id)?.score??null,notes:map.get(s.id)?.notes||'',id:map.get(s.id)?.id}));$('#gradePanel').classList.remove('hidden');$('#gradeTitle').textContent='Calificar: '+a.title;renderGrades();$('#gradePanel').scrollIntoView({behavior:'smooth'})};
function renderGrades(){const max=+activeActivity.max_score,quick=[max,Math.max(max-1,0),Math.max(max-2,0),Math.max(max-3,0),'NP'];$('#gradeList').innerHTML=gradeData.map((s,i)=>`<div class="grade-row"><strong>${s.list_number??'—'}</strong><div>${escapeHtml(s.name)}</div><input type="number" min="0" max="${max}" step="0.1" value="${s.score??''}" data-gi="${i}" class="grade-input"><div class="quick-score">${quick.map(q=>`<button type="button" onclick="quickGrade(${i},'${q}')">${q}</button>`).join('')}</div></div>`).join('');$$('.grade-input').forEach(inp=>inp.oninput=e=>gradeData[+e.target.dataset.gi].score=e.target.value===''?null:+e.target.value)}
window.quickGrade=(i,v)=>{gradeData[i].score=v==='NP'?null:+v;renderGrades()};$('#fillMax').onclick=()=>{gradeData.forEach(x=>x.score=+activeActivity.max_score);renderGrades()};$('#saveGrades').onclick=async()=>{for(const it of gradeData){const row={activity_id:activeActivity.id,student_id:it.student_id,score:it.score,notes:it.notes||''};const old=await MiAulaDB.firstByIndex('grades','unique_key',[activeActivity.id,it.student_id]);if(old)row.id=old.id;await MiAulaDB.put('grades',row)}toast('Calificaciones guardadas');loadSummary()};
window.deleteActivity=async id=>{if(!confirm('¿Eliminar esta actividad y sus calificaciones?'))return;await MiAulaDB.deleteActivity(id);$('#gradePanel').classList.add('hidden');loadActivities();loadSummary();toast('Actividad eliminada')};

async function getScheme(gid,period){const key=`${gid}:${period}`;let s=await MiAulaDB.get('gradingSchemes',key);if(!s){s={key,group_id:gid,period:String(period),work_pct:40,project_pct:40,values_pct:10,attitudes_pct:10,updated_at:new Date().toISOString()};await MiAulaDB.put('gradingSchemes',s)}return s}
async function computeGroupGrading(gid,period){const students=(await MiAulaDB.byIndex('students','group_id',gid)).sort((a,b)=>(a.list_number??9999)-(b.list_number??9999)||a.name.localeCompare(b.name)),activities=await MiAulaDB.byIndex('activities','group_period',[gid,String(period)]),allGrades=await MiAulaDB.all('grades'),actIds=new Set(activities.map(a=>a.id)),grades=allGrades.filter(g=>actIds.has(g.activity_id)),evals=await MiAulaDB.byIndex('evaluations','group_period',[gid,String(period)]),comps=await MiAulaDB.byIndex('studentComponents','group_period',[gid,String(period)]),scheme=await getScheme(gid,period),gByStudent=new Map(),eByStudent=new Map(),cByStudent=new Map(comps.map(c=>[c.student_id,c]));for(const g of grades){if(!gByStudent.has(g.student_id))gByStudent.set(g.student_id,[]);gByStudent.get(g.student_id).push(g)}for(const e of evals){if(!eByStudent.has(e.student_id))eByStudent.set(e.student_id,[]);eByStudent.get(e.student_id).push(e)}const actMap=new Map(activities.map(a=>[a.id,a]));const rows=[];for(const s of students){let workTotal=0,workW=0,projTotal=0,projW=0;for(const g of gByStudent.get(s.id)||[]){if(g.score==null)continue;const a=actMap.get(g.activity_id);if(!a||+a.max_score<=0||+a.weight<=0)continue;const normalized=+g.score*10/+a.max_score,w=+a.weight||1;if(String(a.activity_type).trim().toLowerCase()==='proyecto'){projTotal+=normalized*w;projW+=w}else{workTotal+=normalized*w;workW+=w}}for(const e of eByStudent.get(s.id)||[]){if(e.grade!=null){projTotal+=+e.grade;projW+=1}}const work=workW?workTotal/workW:null,project=projW?projTotal/projW:null,comp=cByStudent.get(s.id),values=comp?.values_score??null,attitudes=comp?.attitudes_score??null;let complete=true,final=0;for(const [score,pct] of [[work,+scheme.work_pct],[project,+scheme.project_pct],[values,+scheme.values_pct],[attitudes,+scheme.attitudes_pct]]){if(pct>0){if(score==null)complete=false;else final+=+score*pct/100}}rows.push({...s,work_avg:work==null?null:+work.toFixed(2),project_avg:project==null?null:+project.toFixed(2),values_score:values,attitudes_score:attitudes,final_grade:complete?+final.toFixed(2):null,complete,notes:comp?.notes||''})}const finals=rows.filter(r=>r.final_grade!=null).map(r=>r.final_grade);return {period:String(period),scheme,students:rows,group_average:finals.length?finals.reduce((a,b)=>a+b,0)/finals.length:null}}
function schemeNumbers(){return {work:+$('#workPct').value||0,project:+$('#projectPct').value||0,values:+$('#valuesPct').value||0,attitudes:+$('#attitudesPct').value||0}}
function updateSchemeUI(){const p=schemeNumbers(),total=p.work+p.project+p.values+p.attitudes;$('#schemeTotal').textContent=total+'%';$('#schemeTotal').parentElement.classList.toggle('bad',Math.abs(total-100)>.001)}['#workPct','#projectPct','#valuesPct','#attitudesPct'].forEach(id=>$(id).addEventListener('input',()=>{updateSchemeUI();if(gradingData)updateAllFinalCells()}));
$('#loadGrading').onclick=loadGrading;$('#gradingGroup').onchange=loadGrading;$('#gradingPeriod').onchange=loadGrading;
async function loadGrading(){const gid=+($('#gradingGroup').value||groups[0]?.id||0);if(!gid){$('#gradingTable').className='empty-state';$('#gradingTable').textContent='Crea o selecciona un grupo.';return}$('#gradingGroup').value=gid;gradingData=await computeGroupGrading(gid,$('#gradingPeriod').value||'1');const s=gradingData.scheme;$('#workPct').value=s.work_pct;$('#projectPct').value=s.project_pct;$('#valuesPct').value=s.values_pct;$('#attitudesPct').value=s.attitudes_pct;updateSchemeUI();$('#gradingGroupAverage').textContent=gradingData.group_average==null?'—':gradingData.group_average.toFixed(2);renderGradingTable();$('#saveComponents').classList.toggle('hidden',!gradingData.students.length)}
function localFinal(s){const p=schemeNumbers(),parts=[[s.work_avg,p.work],[s.project_avg,p.project],[s.values_score,p.values],[s.attitudes_score,p.attitudes]];let total=0;for(const [score,pct] of parts){if(pct>0&&score==null)return null;if(score!=null)total+=+score*pct/100}return Math.round(total*100)/100}
function renderGradingTable(){if(!gradingData?.students.length){$('#gradingTable').className='empty-state';$('#gradingTable').textContent='Este grupo no tiene alumnos.';return}$('#gradingTable').className='table-wrap';$('#gradingTable').innerHTML=`<table><thead><tr><th>No.</th><th>Alumno</th><th>Trabajos</th><th>Proyectos</th><th>Valores</th><th>Actitudes</th><th>Final</th><th>Observación</th></tr></thead><tbody>${gradingData.students.map((s,i)=>`<tr><td>${s.list_number??''}</td><td><strong>${escapeHtml(s.name)}</strong></td><td><span class="auto-score">${s.work_avg??'—'}</span></td><td><span class="auto-score">${s.project_avg??'—'}</span></td><td><input type="number" min="0" max="10" step="0.1" value="${s.values_score??''}" oninput="setGradingValue(${i},'values_score',this.value)"></td><td><input type="number" min="0" max="10" step="0.1" value="${s.attitudes_score??''}" oninput="setGradingValue(${i},'attitudes_score',this.value)"></td><td id="final-${i}"></td><td><input value="${escapeHtml(s.notes||'')}" oninput="setGradingValue(${i},'notes',this.value)"></td></tr>`).join('')}</tbody></table>`;updateAllFinalCells()}
window.setGradingValue=(i,f,v)=>{const s=gradingData.students[i];s[f]=f==='notes'?v:(v===''?null:+v);updateFinalCell(i)};function updateFinalCell(i){const v=localFinal(gradingData.students[i]),el=$(`#final-${i}`);el.innerHTML=v==null?'<span class="pending-score">Pendiente</span>':`<span class="final-score">${v.toFixed(2)}</span>`}function updateAllFinalCells(){gradingData?.students.forEach((_,i)=>updateFinalCell(i))}
$('#schemeForm').onsubmit=async e=>{e.preventDefault();const gid=+$('#gradingGroup').value,p=schemeNumbers(),total=p.work+p.project+p.values+p.attitudes;if(!gid){toast('Selecciona un grupo',true);return}if(Math.abs(total-100)>.001){toast(`Los porcentajes deben sumar 100%. Actualmente suman ${total}%`,true);return}await MiAulaDB.put('gradingSchemes',{key:`${gid}:${$('#gradingPeriod').value}`,group_id:gid,period:$('#gradingPeriod').value,work_pct:p.work,project_pct:p.project,values_pct:p.values,attitudes_pct:p.attitudes,updated_at:new Date().toISOString()});toast('Esquema guardado');loadGrading()};
$('#saveComponents').onclick=async()=>{const gid=+$('#gradingGroup').value,p=$('#gradingPeriod').value;for(const s of gradingData.students)await MiAulaDB.put('studentComponents',{key:`${gid}:${s.id}:${p}`,group_id:gid,student_id:s.id,period:p,values_score:s.values_score==null?null:+s.values_score,attitudes_score:s.attitudes_score==null?null:+s.attitudes_score,notes:s.notes||'',updated_at:new Date().toISOString()});toast('Valores y Actitudes guardados');loadGrading()};$('#fillValues10').onclick=()=>{if(!gradingData)return;gradingData.students.forEach(s=>s.values_score=10);renderGradingTable()};$('#fillAttitudes10').onclick=()=>{if(!gradingData)return;gradingData.students.forEach(s=>s.attitudes_score=10);renderGradingTable()};

function addCriterion(name=''){const type=$('#instrumentType').value,d=document.createElement('div');d.className='criterion-row';d.innerHTML=`<input class="crit-name" placeholder="Ej. Investigación" value="${escapeHtml(name)}"><input class="crit-max" type="number" min="1" max="10" value="${type==='rubric'?4:1}" ${type==='checklist'?'disabled':''}><button type="button" class="btn small">×</button>`;d.querySelector('button').onclick=()=>d.remove();$('#criteriaRows').appendChild(d)}$('#addCriterion').onclick=()=>addCriterion();$('#instrumentType').onchange=()=>$$('.crit-max').forEach(x=>{x.value=$('#instrumentType').value==='rubric'?4:1;x.disabled=$('#instrumentType').value==='checklist'});
$('#instrumentForm').onsubmit=async e=>{e.preventDefault();const criteria=$$('.criterion-row').map((r,i)=>({id:'c'+(i+1),name:r.querySelector('.crit-name').value.trim(),max:+r.querySelector('.crit-max').value||1})).filter(c=>c.name);if(!criteria.length){toast('Agrega al menos un criterio',true);return}await MiAulaDB.add('instruments',{name:$('#instrumentName').value.trim(),instrument_type:$('#instrumentType').value,criteria,convert_to_grade:$('#convertGrade').checked?1:0,created_at:new Date().toISOString()});$('#instrumentName').value='';$('#criteriaRows').innerHTML='';addCriterion();await loadInstruments();toast('Instrumento guardado')};
async function loadInstruments(){instruments=(await MiAulaDB.all('instruments')).sort((a,b)=>b.id-a.id);$('#instrumentCards').innerHTML=instruments.length?instruments.map(i=>`<div class="instrument-card"><div><strong>${escapeHtml(i.name)}</strong><br><small>${i.instrument_type==='rubric'?'Rúbrica':'Lista de cotejo'} · ${i.criteria.length} criterios · ${i.convert_to_grade?'0–10':'evidencia'}</small></div><button class="btn small danger" onclick="deleteInstrument(${i.id})">Eliminar</button></div>`).join(''):'<div class="empty-state">Crea tu primer instrumento.</div>';$('#evalInstrument').innerHTML='<option value="">Seleccionar…</option>'+instruments.map(i=>`<option value="${i.id}">${escapeHtml(i.name)}</option>`).join('')}
window.deleteInstrument=async id=>{const used=await MiAulaDB.byIndex('evaluations','instrument_id',id);if(used.length){toast('No se puede eliminar: ya tiene evaluaciones registradas.',true);return}if(!confirm('¿Eliminar este instrumento?'))return;await MiAulaDB.remove('instruments',id);loadInstruments();toast('Instrumento eliminado')};
$('#evalGroup').onchange=()=>{loadEvalStudents();loadEvalHistory()};$('#evalInstrument').onchange=renderEvalCriteria;async function loadEvalStudents(){const gid=+$('#evalGroup').value;if(!gid){$('#evalStudents').className='student-picker empty-state';$('#evalStudents').textContent='Selecciona un grupo.';return}const s=(await MiAulaDB.byIndex('students','group_id',gid)).sort((a,b)=>(a.list_number??9999)-(b.list_number??9999)||a.name.localeCompare(b.name));$('#evalStudents').className='student-picker';$('#evalStudents').innerHTML=s.map(x=>`<label class="student-pick"><input type="checkbox" value="${x.id}"><span><strong>${x.list_number??'—'}</strong> · ${escapeHtml(x.name)}</span></label>`).join('')}
function renderEvalCriteria(){const inst=instruments.find(i=>i.id===+$('#evalInstrument').value);if(!inst){$('#evalCriteria').className='empty-state';$('#evalCriteria').textContent='Selecciona un instrumento.';return}$('#evalCriteria').className='';$('#evalCriteria').innerHTML=inst.criteria.map(c=>inst.instrument_type==='rubric'?`<div class="criterion-eval" data-cid="${c.id}" data-type="rubric"><strong>${escapeHtml(c.name)}</strong><div class="level-buttons">${Array.from({length:c.max},(_,k)=>k+1).map(v=>`<button type="button" data-value="${v}" onclick="pickLevel(this)">${v}</button>`).join('')}</div></div>`:`<div class="criterion-eval" data-cid="${c.id}" data-type="checklist"><strong>${escapeHtml(c.name)}</strong><div class="level-buttons"><button type="button" data-value="0" onclick="pickLevel(this)">No</button><button type="button" data-value="1" onclick="pickLevel(this)">Sí</button></div></div>`).join('')}window.pickLevel=el=>{el.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));el.classList.add('active')};
$('#saveEvaluation').onclick=async()=>{const gid=+$('#evalGroup').value,iid=+$('#evalInstrument').value,title=$('#evalTitle').value.trim(),ids=$$('#evalStudents input:checked').map(x=>+x.value),inst=instruments.find(i=>i.id===iid);if(!gid||!iid||!title||!ids.length){toast('Selecciona grupo, instrumento, título y al menos un alumno',true);return}const details={};let raw=0,max=0,incomplete=false;$$('#evalCriteria .criterion-eval').forEach(c=>{const b=c.querySelector('button.active');if(!b){incomplete=true;return}const val=c.dataset.type==='checklist'?(b.dataset.value==='1'?1:0):+b.dataset.value;details[c.dataset.cid]=val;raw+=val;const crit=inst.criteria.find(x=>x.id===c.dataset.cid);max+=inst.instrument_type==='checklist'?1:+crit.max});if(incomplete){toast('Evalúa todos los criterios',true);return}const grade=inst.convert_to_grade&&max?Math.round(raw/max*1000)/100:null;for(const sid of ids)await MiAulaDB.add('evaluations',{group_id:gid,instrument_id:iid,title,student_id:sid,team_name:$('#evalTeam').value.trim(),raw_score:raw,grade,details,notes:$('#evalNotes').value.trim(),evaluation_date:$('#evalDate').value,period:$('#evalPeriod').value,created_at:new Date().toISOString()});toast('Evaluación guardada'+(grade!=null?` · ${grade.toFixed(2)}`:''));$$('#evalStudents input').forEach(x=>x.checked=false);$('#evalNotes').value='';loadEvalHistory();loadSummary()};
async function loadEvalHistory(){const gid=+$('#evalGroup').value;if(!gid){$('#evalHistory').innerHTML='<div class="empty-state">Selecciona un grupo.</div>';return}const evals=(await MiAulaDB.byIndex('evaluations','group_id',gid)).sort((a,b)=>b.id-a.id),students=await MiAulaDB.byIndex('students','group_id',gid),sm=new Map(students.map(s=>[s.id,s])),im=new Map(instruments.map(i=>[i.id,i]));$('#evalHistory').innerHTML=evals.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Trim.</th><th>Alumno</th><th>Evaluación</th><th>Instrumento</th><th>Calif.</th><th></th></tr></thead><tbody>${evals.slice(0,80).map(e=>`<tr><td>${e.evaluation_date||''}</td><td>${e.period||'1'}</td><td>${escapeHtml(sm.get(e.student_id)?.name||'')}</td><td>${escapeHtml(e.title)}</td><td>${escapeHtml(im.get(e.instrument_id)?.name||'')}</td><td><strong>${e.grade??''}</strong></td><td><button class="btn small danger" onclick="deleteEvaluation(${e.id})">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">Todavía no hay evaluaciones.</div>'}
window.deleteEvaluation=async id=>{if(!confirm('¿Eliminar esta evaluación?'))return;await MiAulaDB.remove('evaluations',id);loadEvalHistory();loadSummary();toast('Evaluación eliminada')};

async function buildWorkbook(gid){const g=await MiAulaDB.get('groups',gid);if(!g)throw new Error('Grupo no encontrado');const students=(await MiAulaDB.byIndex('students','group_id',gid)).sort((a,b)=>(a.list_number??9999)-(b.list_number??9999)||a.name.localeCompare(b.name)),attendance=(await MiAulaDB.byIndex('attendance','group_id',gid)).sort((a,b)=>a.attendance_date.localeCompare(b.attendance_date)),activities=(await MiAulaDB.byIndex('activities','group_id',gid)).sort((a,b)=>String(a.period).localeCompare(String(b.period))||String(a.activity_date).localeCompare(String(b.activity_date))),allGrades=await MiAulaDB.all('grades'),actIds=new Set(activities.map(a=>a.id)),grades=allGrades.filter(x=>actIds.has(x.activity_id)),evals=(await MiAulaDB.byIndex('evaluations','group_id',gid)).sort((a,b)=>String(a.period).localeCompare(String(b.period))||String(a.evaluation_date).localeCompare(String(b.evaluation_date))),insts=await MiAulaDB.all('instruments'),im=new Map(insts.map(i=>[i.id,i])),sm=new Map(students.map(s=>[s.id,s])),am=new Map(activities.map(a=>[a.id,a])),gradeKey=new Map(grades.map(gr=>[`${gr.activity_id}:${gr.student_id}`,gr])),dates=[...new Set(attendance.map(a=>a.attendance_date))].sort(),attKey=new Map(attendance.map(a=>[`${a.student_id}:${a.attendance_date}`,a.status]));const grading={};for(const p of ['1','2','3'])grading[p]=await computeGroupGrading(gid,p);const schemes=grading;
const avgFinal=p=>{const v=grading[p].students.filter(x=>x.final_grade!=null).map(x=>x.final_grade);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null};const resumo=[['Indicador','Valor'],['Grupo',g.name],['Grado',g.grade||''],['Disciplina',g.discipline||''],['Ciclo escolar',g.school_year||''],['Alumnos',students.length],['Registros de asistencia',attendance.length],['Promedio final Trimestre 1',avgFinal('1')],['Promedio final Trimestre 2',avgFinal('2')],['Promedio final Trimestre 3',avgFinal('3')],['Generado',new Date().toLocaleString('es-MX')]];
const esquema=[['Trimestre','Trabajos %','Proyectos %','Valores %','Actitudes %','Total %']];for(const p of ['1','2','3']){const s=schemes[p].scheme;esquema.push([p,s.work_pct,s.project_pct,s.values_pct,s.attitudes_pct,+s.work_pct+ +s.project_pct+ +s.values_pct+ +s.attitudes_pct])}
const trim=[['No.','Código','Alumno','Trimestre','Trabajos','Trabajos %','Proyectos','Proyectos %','Valores','Valores %','Actitudes','Actitudes %','Final','Estado','Observación']];for(const p of ['1','2','3']){const sc=grading[p].scheme;for(const s of grading[p].students)trim.push([s.list_number,s.student_code,s.name,p,s.work_avg,sc.work_pct,s.project_avg,sc.project_pct,s.values_score,sc.values_pct,s.attitudes_score,sc.attitudes_pct,s.final_grade,s.complete?'Completo':'Pendiente',s.notes||''])}
const conc=[['No.','Código','Alumno','Grado','Asistencia %',...activities.map(a=>`${a.title} [T${a.period}]`),'Prom. actividades','T1','T2','T3']];for(const s of students){const sa=attendance.filter(a=>a.student_id===s.id),attPct=sa.length?Math.round(1000*sa.filter(a=>a.status!=='F').length/sa.length)/10:null,normalized=[];const row=[s.list_number,s.student_code,s.name,s.grade||'',attPct];for(const a of activities){const gr=gradeKey.get(`${a.id}:${s.id}`),v=gr?.score??null;row.push(v);if(v!=null&&+a.max_score>0)normalized.push(+v*10/+a.max_score)}row.push(normalized.length?Math.round(100*normalized.reduce((x,y)=>x+y,0)/normalized.length)/100:null,grading['1'].students.find(x=>x.id===s.id)?.final_grade??null,grading['2'].students.find(x=>x.id===s.id)?.final_grade??null,grading['3'].students.find(x=>x.id===s.id)?.final_grade??null);conc.push(row)}
const asist=[['No.','Alumno',...dates]];for(const s of students)asist.push([s.list_number,s.name,...dates.map(d=>attKey.get(`${s.id}:${d}`)||'')]);
const acts=[['Actividad','Tipo','Trimestre','Fecha','Puntaje máximo','Peso','Capturadas','Pendientes']];for(const a of activities){const count=grades.filter(gr=>gr.activity_id===a.id&&gr.score!=null).length;acts.push([a.title,a.activity_type,a.period,a.activity_date,a.max_score,a.weight,count,Math.max(students.length-count,0)])}
const detail=[['No.','Alumno','Actividad','Tipo','Trimestre','Fecha','Calificación','Máximo','Equivalente 0-10','Observación']];for(const gr of grades){const a=am.get(gr.activity_id),s=sm.get(gr.student_id);if(!a||!s)continue;detail.push([s.list_number,s.name,a.title,a.activity_type,a.period,a.activity_date,gr.score,a.max_score,gr.score==null?null:Math.round(+gr.score*1000/+a.max_score)/100,gr.notes||''])}
const evalSheet=[['Fecha','Trimestre','Alumno','Evaluación','Instrumento','Tipo','Equipo','Puntaje','Calificación','Observación']];for(const e of evals){const i=im.get(e.instrument_id);evalSheet.push([e.evaluation_date,e.period,sm.get(e.student_id)?.name||'',e.title,i?.name||'',i?.instrument_type==='rubric'?'Rúbrica':'Lista de cotejo',e.team_name||'',e.raw_score,e.grade,e.notes||''])}
const obs=[['Alumno','Origen','Actividad/Evaluación','Observación']];for(const gr of grades){if(String(gr.notes||'').trim()){const a=am.get(gr.activity_id),s=sm.get(gr.student_id);obs.push([s?.name||'','Actividad',a?.title||'',gr.notes])}}for(const e of evals){if(String(e.notes||'').trim())obs.push([sm.get(e.student_id)?.name||'','Evaluación',e.title,e.notes])}for(const p of ['1','2','3'])for(const s of grading[p].students)if(String(s.notes||'').trim())obs.push([s.name,`Trimestre ${p}`,'Valores y Actitudes',s.notes]);return {sheets:[{name:'Resumen',rows:resumo},{name:'Esquemas',rows:esquema},{name:'Calificación trimestral',rows:trim},{name:'Concentrado',rows:conc},{name:'Asistencia',rows:asist},{name:'Actividades',rows:acts},{name:'Detalle calificaciones',rows:detail},{name:'Evaluaciones',rows:evalSheet},{name:'Observaciones',rows:obs}]}}
$('#exportBtn').onclick=async()=>{const gid=+$('#exportGroup').value;if(!gid){toast('Selecciona un grupo',true);return}try{toast('Generando Excel…');const g=await MiAulaDB.get('groups',gid),book=await buildWorkbook(gid),blob=XLSXLite.write(book),safe=String(g.name).replace(/[^A-Za-z0-9_-]+/g,'_');downloadBlob(blob,`MiAula_${safe}_${today}.xlsx`);toast('Excel generado')}catch(e){toast(e.message,true)}};
$('#backupBtn').onclick=async()=>{const data=await MiAulaDB.exportBackup(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});downloadBlob(blob,`MiAula_Respaldo_${new Date().toISOString().replace(/[:.]/g,'-')}.json`);toast('Respaldo generado')};
$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!confirm('Restaurar este respaldo reemplazará los datos actuales de la tablet. ¿Continuar?')){e.target.value='';return}await MiAulaDB.restoreBackup(data);await refreshGroups();await loadInstruments();await loadSummary();toast('Respaldo restaurado correctamente');goView('dashboard')}catch(er){toast(er.message,true)}finally{e.target.value=''}};

window.addEventListener('error',e=>{console.error(e.error||e.message);const b=$('#fatalBanner');b.textContent='Error de interfaz: '+(e.message||'desconocido');b.classList.remove('hidden')});
init();
